spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
oauth2:
  provider:
    google: ${GOOGLE}
    kakao: ${KAKAO}
    
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
