name: Cypress Tests
on:
  pull_request:
    branches:
      - develop
    paths:
      - .github/**
      - frontend-monorepo/packages/hanglog-service/**

defaults:
  run:
    working-directory: frontend-monorepo/packages/hanglog-service
jobs:
  run-dev:
    if: contains(github.event.pull_request.labels.*.name, 'FE-Service')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build design-system
        run: yarn run build:design-system

      - name: Create env file
        run: |
          touch .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
          echo GOOGLE_MAP_ID=${{ secrets.GOOGLE_MAP_ID }} >> .env
          echo PROD_BASE_URL=${{ secrets.PROD_BASE_URL }} >> .env
          cat .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn run serve:dev
          wait-on: "http://localhost:3000"
          record: false
          working-directory: ./frontend-monorepo/packages/hanglog-service
          install-command: yarn install
          command: yarn run --binaries-only cypress run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress test failure message
        if: failure()
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            로컬 cypress 테스트가 실패했습니다. [테스트 결과 자세히 보기](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
